In [33]:
import pandas as pd
import numpy as np
import sklearn as sl
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split

In [34]:
abalone = pd.read_csv("/Users/normalazo/Desktop/env1/Untitled Folder/abalone.data.csv",header=None)

In [35]:
abalone.describe()

1            2            3            4            5  \
count  4177.000000  4177.000000  4177.000000  4177.000000  4177.000000   
mean      0.523992     0.407881     0.139516     0.828742     0.359367   
std       0.120093     0.099240     0.041827     0.490389     0.221963   
min       0.075000     0.055000     0.000000     0.002000     0.001000   
25%       0.450000     0.350000     0.115000     0.441500     0.186000   
50%       0.545000     0.425000     0.140000     0.799500     0.336000   
75%       0.615000     0.480000     0.165000     1.153000     0.502000   
max       0.815000     0.650000     1.130000     2.825500     1.488000   

                 6            7            8  
count  4177.000000  4177.000000  4177.000000  
mean      0.180594     0.238831     9.933684  
std       0.109614     0.139203     3.224169  
min       0.000500     0.001500     1.000000  
25%       0.093500     0.130000     8.000000  
50%       0.171000     0.234000     9.000000  
75%       0.253000     0.329000    11.000000  
max       0.760000     1.005000    29.000000

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(abalone[abalone.columns[1:8]], abalone[[0]], train_size=0.75)
X_train, X_test, Y_train, Y_test = np.asarray(X_train), np.asarray(X_test), np.asarray(Y_train), np.asarray(Y_test)

In [37]:
class_num=[]
for i in range (0,3132):
    if (Y_train[i]=="I"):
        class_num.append(0)
    elif(Y_train[i]=="F"):
        class_num.append(1)
    else:
        class_num.append(2)

In [38]:
class_num_test=[]
for i in range (0,1045):
    if (Y_train[i]=="I"):
        class_num_test.append(0)
    elif(Y_train[i]=="F"):
        class_num_test.append(1)
    else:
        class_num_test.append(2)

In [39]:
class_num=np.asarray(class_num)
class_num_test=np.asarray(class_num_test)


In [40]:
class_num=class_num.reshape((3132,1))

In [41]:
class_num_test=class_num_test.reshape((1045,1))

In [42]:
X_train=np.concatenate((X_train,class_num),axis=1)

In [43]:
X_test=np.concatenate((X_test,class_num_test),axis=1)


In [44]:
clusters_ab = KMeans(init="k-means++", n_clusters=3, n_init=10)
clusters_ab.fit_predict(X_train)

array([2, 2, 2, ..., 0, 0, 2], dtype=int32)

In [45]:
centroids_ab = clusters_ab.cluster_centers_
centroids_ab

array([[ 0.42567172,  0.32492929,  0.10748485,  0.42284646,  0.18830202,
         0.09029242,  0.12538939,  0.0040404 ],
       [ 0.56207899,  0.43997396,  0.15178819,  0.99567014,  0.43377344,
         0.21647005,  0.28341536,  2.        ],
       [ 0.58019192,  0.45583333,  0.15764141,  1.05147374,  0.44792626,
         0.23194293,  0.30259949,  0.99090909]])

In [46]:
predictions_ab=clusters_ab.predict(X_test)

In [47]:
#class_num_test
confusion_ab = confusion_matrix(class_num_test, predictions_ab)
confusion_ab

array([[290,   0,  52],
       [ 20,   0, 304],
       [  0, 379,   0]])

In [48]:
from sklearn.metrics import accuracy_score

accuracy_score(class_num_test, predictions_ab)

0.27751196172248804

In [49]:
from sklearn.metrics import classification_report

target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(class_num_test, predictions_ab, target_names=target_names))

             precision    recall  f1-score   support

    class 0       0.94      0.85      0.89       342
    class 1       0.00      0.00      0.00       324
    class 2       0.00      0.00      0.00       379

avg / total       0.31      0.28      0.29      1045

